In [38]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [39]:
df=pd.read_csv('play_tennis.csv')

In [40]:
df.head()

  day   outlook  temp humidity    wind play
0  D1     Sunny   Hot     High    Weak   No
1  D2     Sunny   Hot     High  Strong   No
2  D3  Overcast   Hot     High    Weak  Yes
3  D4      Rain  Mild     High    Weak  Yes
4  D5      Rain  Cool   Normal    Weak  Yes

In [41]:
cross_tab=pd.crosstab(df['play'],df['outlook'])
print(cross_tab)

outlook  Overcast  Rain  Sunny
play
No              0     2      3
Yes             4     3      2

In [42]:
from sklearn.preprocessing import LabelEncoder

# Initialize label encoder
label_encoder = LabelEncoder()

# Drop the 'day' column (not needed for classification)
df_clean = df.drop('day', axis=1)

# Apply label encoding to each of the categorical columns
for col in ['outlook', 'temp', 'humidity', 'wind', 'play']:
    df_clean[col] = label_encoder.fit_transform(df_clean[col])

# Display the cleaned and encoded data
df_clean.head()

   outlook  temp  humidity  wind  play
0        2     1         0     1     0
1        2     1         0     0     0
2        0     1         0     1     1
3        1     2         0     1     1
4        1     0         1     1     1

In [44]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score

# Split the data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Train the model
nb_sklearn = GaussianNB()
nb_sklearn.fit(X_train, y_train)

# Make predictions
y_pred = nb_sklearn.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy}')

Accuracy: 0.6

In [60]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB,MultinomialNB,BernoulliNB
from sklearn.metrics import accuracy_score

y=df_clean.iloc[:, -1]
X=df_clean.iloc[:, 1:-1]

X_train,X_test,y_train,y_test =train_test_split(X,y,test_size=0.3)

nb_model=GaussianNB()
nb_model.fit(X_train,y_train)

y_predict=nb_model.predict(X_test)
accuracy=accuracy_score(y_test,y_predict)
print(accuracy)

nb_model=MultinomialNB()
nb_model.fit(X_train,y_train)

y_predict=nb_model.predict(X_test)
accuracy=accuracy_score(y_test,y_predict)
print(accuracy)

nb_model=BernoulliNB()
nb_model.fit(X_train,y_train)

y_predict=nb_model.predict(X_test)

accuracy=accuracy_score(y_test,y_predict)
print(accuracy)

correlation=df_clean.corr()
print(correlation)

0.8
0.6
0.8
           outlook      temp      humidity          wind      play
outlook   1.000000  0.092036 -8.944272e-02  7.745967e-02 -0.493333
temp      0.092036  1.000000 -5.144958e-01 -2.475369e-02 -0.051131
humidity -0.089443 -0.514496  1.000000e+00 -6.409876e-17  0.447214
wind      0.077460 -0.024754 -6.409876e-17  1.000000e+00  0.258199
play     -0.493333 -0.051131  4.472136e-01  2.581989e-01  1.000000

In [48]:
print(df[df.columns[-1]])

0      No
1      No
2     Yes
3     Yes
4     Yes
5      No
6     Yes
7      No
8     Yes
9     Yes
10    Yes
11    Yes
12    Yes
13     No
Name: play, dtype: object

In [49]:
df.iloc[:, -1]

0      No
1      No
2     Yes
3     Yes
4     Yes
5      No
6     Yes
7      No
8     Yes
9     Yes
10    Yes
11    Yes
12    Yes
13     No
Name: play, dtype: object

In [57]:
df.iloc[:, 1:-1]

     outlook  temp humidity    wind
0      Sunny   Hot     High    Weak
1      Sunny   Hot     High  Strong
2   Overcast   Hot     High    Weak
3       Rain  Mild     High    Weak
4       Rain  Cool   Normal    Weak
5       Rain  Cool   Normal  Strong
6   Overcast  Cool   Normal  Strong
7      Sunny  Mild     High    Weak
8      Sunny  Cool   Normal    Weak
9       Rain  Mild   Normal    Weak
10     Sunny  Mild   Normal  Strong
11  Overcast  Mild     High  Strong
12  Overcast   Hot   Normal    Weak
13      Rain  Mild     High  Strong